apiVersion: v1
kind: Service
metadata:
  name: {{ include "emt-app.backendServiceName" . }}
  namespace: {{ include "emt-app.namespace" . }}
  labels:
    {{- include "emt-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "emt-app.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
