apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emt-app.frontendServiceName" . }}
  namespace: {{ include "emt-app.namespace" . }}
  labels:
    {{- include "emt-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "emt-app.componentLabels" (dict "root" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "emt-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "emt-app.frontendConfigMapName" . }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
