{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "emt-app.fullname" . }}
  namespace: {{ include "emt-app.namespace" . }}
  labels:
    {{- include "emt-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.backend.path }}
            pathType: {{ .Values.ingress.backend.pathType }}
            backend:
              service:
                name: {{ include "emt-app.backendServiceName" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: {{ .Values.ingress.frontend.path }}
            pathType: {{ .Values.ingress.frontend.pathType }}
            backend:
              service:
                name: {{ include "emt-app.frontendServiceName" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
